# Generated by Django 3.0.5 on 2020-05-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('num_control', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom_alu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('clave_mae', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nomb_mae', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('clave_mat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom_mat', models.CharField(max_length=40)),
                ('clave_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.CharField(max_length=30)),
                ('asist', models.BooleanField()),
                ('fecha', models.DateField()),
                ('clave_matA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Materias')),
            ],
        ),
    ]
