# Generated by Django 3.0.5 on 2020-05-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0003_auto_20200516_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('clave_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Materias', verbose_name='Datos de la materia')),
            ],
        ),
    ]
