# Generated by Django 3.0.5 on 2020-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0004_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='dia',
            field=models.CharField(max_length=30),
        ),
    ]
