# Generated by Django 3.0.5 on 2020-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0006_auto_20200518_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='hora',
            new_name='horaF',
        ),
        migrations.AddField(
            model_name='horarios',
            name='horaI',
            field=models.TimeField(default='14:00:00'),
            preserve_default=False,
        ),
    ]
