# Generated by Django 3.0.5 on 2020-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0007_auto_20200518_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='nom_alu',
            field=models.CharField(default='Manuel Fierro', max_length=30, verbose_name='Nombre del Alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='num_control',
            field=models.CharField(max_length=30, verbose_name='Número de Control/Nombre'),
        ),
    ]
