# Generated by Django 3.0.5 on 2020-05-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0009_auto_20200520_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentes',
            old_name='clave_mae',
            new_name='clave_doc',
        ),
        migrations.RenameField(
            model_name='docentes',
            old_name='nomb_mae',
            new_name='nom_doc',
        ),
        migrations.RenameField(
            model_name='materias',
            old_name='clave_mae',
            new_name='clave_doc',
        ),
    ]
